spring.application.name=Fruits-veggies

spring.datasource.url=jdbc:mysql://localhost:3306/fruits_db
spring.datasource.username=root
spring.datasource.password="T#9v$X2Lm@8!QpZ5"

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
